# Generated by Django 3.2 on 2022-11-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=50, verbose_name='DNI')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
